#!/bin/bash
echo ""
echo "========================================="
echo "    INFORMAÇÕES DA MÁQUINA"
echo "========================================="
echo "• Hostname.....: $(hostname)"
echo "• Sistema......: $(lsb_release -d | cut -f2)"
echo "• Kernel.......: $(uname -r)"
echo "• Arquitetura..: $(arch)"
echo "• Processador..: $(nproc) cores"
echo "• CPU..........: $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {printf "%.1f%%", usage}') usado"
echo "• Load Average.: $(uptime | awk -F'load average:' '{print $2}' | xargs)"
echo "• Memória......: $(free -h | grep Mem | awk '{print $3}') / $(free -h | grep Mem | awk '{print $2}') ($(free | grep Mem | awk '{printf "%.1f%%", $3/$2 * 100}') usado)"
echo "• Disco........: $(df -h / | awk 'NR==2 {print $3}') / $(df -h / | awk 'NR==2 {print $2}') ($(df -h / | awk 'NR==2 {print $5}') usado)"
echo "• Uptime.......: $(uptime -p)"
echo "• Usuário......: $(whoami)"
echo "• IPs..........: $(hostname -I)"
echo "========================================="